#!/usr/bin/env bash
set -e

DEFAULT_CONFIG_PATH="/peerid-gui/.env"

sed -i "s|DEV_API_ROUTE.*|DEV_API_ROUTE='$DEV_API_ROUTE'|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PRODUCTION_API_ROUTE.*|PRODUCTION_API_ROUTE='$PRODUCTION_API_ROUTE'|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|DEV_BASE_ROUTE.*|DEV_BASE_ROUTE='$DEV_BASE_ROUTE'|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PRODUCTION_BASE_ROUTE.*|PRODUCTION_BASE_ROUTE='$PRODUCTION_BASE_ROUTE'|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|BLOCKCHAIN_ENDPOINTS.*|BLOCKCHAIN_ENDPOINTS='$BLOCKCHAIN_ENDPOINTS'|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_USD_ASSET_ID.*|PEERPLAYS_USD_ASSET_ID='$PEERPLAYS_USD_ASSET_ID'|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_ESCROW_ACCOUNT_ID.*|PEERPLAYS_ESCROW_ACCOUNT_ID='$PEERPLAYS_ESCROW_ACCOUNT_ID'|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_PAYMENT_ACCOUNT_ID.*|PEERPLAYS_PAYMENT_ACCOUNT_ID='$PEERPLAYS_PAYMENT_ACCOUNT_ID'|g" "${DEFAULT_CONFIG_PATH}"

exec "$@"
